# Generated by Django 6.0.1 on 2026-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
